### ISSUE TITLE
看起来有bug  我是批量去掉了所有的https://和 http:// 结果好像开始错误了  结果应该是自动报错是https还是http的

### ISSUE THREAD

**Issue by soshunte** [HackAllSec/hfinger#3]
看起来有bug  我是批量去掉了所有的https://和 http:// 结果好像开始错误了  结果应该是自动报错是https还是http的

**Comment by NHPT** [comment]
提供一些细节呗

**Comment by soshunte** [comment]
不加https://或者是http:// 就全是红色的

NHPT ***@***.***> 于2024年8月19日周一 13:44写道：

**Comment by NHPT** [comment]
肯定啊  这是正常的  需要加http或者https，程序不会自动添加的
